Falcon-819 falcon bugs for Entity SLA Alerts
InMobi/falcon pull request #57
Opened 2018-07-27 07:12 UTC by amitkhanna1806

2018-07-27 07:21 UTC, sandeepSamudrala commented
Is the build fully successful with all tests passing?

2018-07-27 07:22 UTC, sandeepSamudrala requested changes
Can you also publish the new DB entries you are seeing post the changes?
Publish the test cases you have validated over here.

2018-07-27 07:22 UTC, sandeepSamudrala commented on prism/src/main/java/org/apache/falcon/service/EntitySLAAlertService.java
> +                            LOG.info("Entity : {} Cluster : {} Nominal Time : {} missed SLALow is already present in DB"
make it debug

2018-07-27 07:22 UTC, sandeepSamudrala commented on prism/src/main/java/org/apache/falcon/jdbc/MonitoringJdbcStateStore.java
> +    public List<EntitySLAAlertBean> getEntityAlertList(String entityName, String clusterName, Date nominalTime,
Rename this method to getAlertInstancesList

2018-07-27 07:22 UTC, sandeepSamudrala commented on prism/src/main/java/org/apache/falcon/service/EntitySLAAlertService.java
> +                            LOG.info("Entity : {} Cluster : {} Nominal Time : {} missed SLALow is already present in DB"
space after SLA

2018-07-30 06:53 UTC, amitkhanna1806 commented
Table entry at certain point
| id     | cluster_name | entity_name  | entity_type | sla_high_missed | sla_low_missed | nominal_time        | sla_high_alert_sent | sla_low_alert_sent |
+--------+--------------+--------------+-------------+-----------------+----------------+---------------------+---------------------+--------------------+
| 553471 | ev1-xenon    | dummy-feed-4 | feed        |               0 |              1 | 2018-07-30 04:45:00 | NULL                | NULL               |
| 553472 | ev1-xenon    | dummy-feed-4 | feed        |               0 |              1 | 2018-07-30 05:00:00 | NULL                | NULL               |
| 553473 | ev1-xenon    | dummy-feed-4 | feed        |               0 |              1 | 2018-07-30 05:15:00 | NULL                | NULL               |
| 553474 | ev1-xenon    | dummy-feed-4 | feed        |               0 |              1 | 2018-07-30 05:30:00 | NULL                | NULL               |

test cases - 
1) Entity SLA Low missed
2) Entity SLA High missed
3) checking size of list of instances when entity has emitted metric to be zero.

2018-07-30 07:11 UTC, pallavi-rao requested changes

2018-07-30 07:11 UTC, pallavi-rao commented on prism/src/main/java/org/apache/falcon/service/EntitySLAMonitoringService.java
> +        if (entityType.equalsIgnoreCase(EntityType.FEED.toString())) {
Use ` if (entity.getEntityType() == EntityType.FEED) {`

2018-07-30 07:11 UTC, pallavi-rao commented on prism/src/main/java/org/apache/falcon/jdbc/MonitoringJdbcStateStore.java
> +    public List<EntitySLAAlertBean> getAlertInstancesList(String entityName, String clusterName, Date nominalTime,
Why is this a list? For the given set of params, there can be only one entry. The entry may have SLALow miss or SLAHigh miss. But, there should be only one entry. Right?

2018-07-30 07:11 UTC, pallavi-rao commented on prism/src/main/java/org/apache/falcon/service/EntitySLAAlertService.java
> +                        if (store.getAlertInstancesList(entityName, clusterName, nominalTime, entityType).size() == 0){
Basically, you need a putIfAbsent kind of functionality. It would be better to add such a method to the store itself.

2018-07-30 10:01 UTC, pallavi-rao approved these changes

2018-07-30 11:01 UTC, merged